Adds Command Line Interface
moclojer/moclojer pull request #65
Opened 2022-09-26 21:49 UTC by rafaeldelboni

Adds the following arguments to CLI:
```bash
Moclojer (0.1), simple and efficient HTTP mock server.
  -c, --config  <file> moclojer.yml Config path <file> or the CONFIG environment variable.
  -m, --mocks   <file>              OpenAPI v3 mocks path <file> or the MOCKS environment variable.
  -v, --version                     Show version.
  -h, --help                        Show this Help.
```
Works on `clj -M:run`, `java -jar moclojer.jar` and `moclojer_bin`.

Closes #62

2022-09-26 22:06 UTC, rafaeldelboni commented
Hold this PR I will do some unit tests for it.

2022-09-28 14:46 UTC, matheusfrancisco approved these changes
LGTM.
Could you add those instructions to the readme?

2022-09-29 09:03 UTC, avelino requested changes
Important to update the documentation and put example in the readme (simple, like you did in the body of the pull request).

Sorry the documentation is not in this repository - I will work on unifying the documentation and project repository to simplify the contribution.

https://github.com/avelino/avelino.run/blob/main/content/projects/moclojer.md

2022-09-29 19:31 UTC, avelino approved these changes
LGTM

2022-09-29 19:31 UTC, merged